version: "0.19"
services:
  aplicacion:
    container_name: aplicacionGim
    build: .
    ports:
      - "5000:5000"
    links:
      - Psql
  Psql:
    image: postgres:16.1
    container_name: PsqlGim
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= Nico0603
      - POSTGRES_DB= gimnasio

    volumes:
      - pgData:/var/lib/postgresql/data

volumes:
  pgData: