version: '3.12'

services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "Main.py"]
    depends_on:
      - db
    environment:
      - _HOST=db
      - _DATABASE=gimnasio
      - _USERNAME=postgres
      - _PASSWORD=Nico0603
      - _DB_PORT=5432



  db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nico0603
      POSTGRES_DB: gimnasio
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: